[colors.primary]
foreground = "#f8eaea"
# background = "#191724"
# dim_foreground = "#cfcfd6"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#f8eaea"
cursor = "#524f67"

[colors.vi_mode_cursor]
text = "#f8eaea"
cursor = "#524f67"

[colors.search.matches]
foreground = "#f8eaea"
background = "#3a334a"

[colors.search.focused_match]
foreground = "#191724"
background = "#ff4f6d"

[colors.hints.start]
foreground = "#f8eaea"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#cfcfd6"
background = "#1f1d2e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.selection]
text = "#e0def4"
background = "#2a2742"

[colors.normal]
black = "#1a1826"
white = "#f8eaea"
red = "#ff4f6d"
green = "#00f5d4"
blue = "#c8616f"
yellow = "#ffb703"
magenta = "#ff80ab"
cyan = "#9aa0b8"

[colors.bright]
black = "#2a2742"
white = "#ffffff"
red = "#ff7a8a"
green = "#4dffe6"
blue = "#e0727e"
yellow = "#ffd75a"
magenta = "#ffd1d7"
cyan = "#b4b8d4"

[colors.dim]
black = "#191724"
white = "#cfcfd6"
red = "#d95465"
green = "#00a37a"
blue = "#a85561"
yellow = "#cc9600"
magenta = "#e1959f"
cyan = "#767a90"
