# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#e6e6e6"
# background = "#191724"
# dim_foreground = "#908caa"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.search.matches]
foreground = "#e0def4"
background = "#2a2742"

[colors.search.focused_match]
foreground = "#191724"
background = "#fc5f72"

[colors.hints.start]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#a9a4c7"
background = "#1f1d2e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.selection]
text = "#e0def4"
background = "#2a2742"

[colors.normal]
black = "#1f1d2e"
white = "#e6e6e6"
red = "#fc5f72"
green = "#00ffb0"
blue = "#c8616f"
yellow = "#f6c117"
magenta = "#ffadb8"
cyan = "#8b8fa6"

[colors.bright]
black = "#2a2742"
white = "#ffffff"
red = "#ff7a8a"
green = "#4dffd0"
blue = "#e0727e"
yellow = "#ffdd4d"
magenta = "#ffd1d7"
cyan = "#a3a7bf"

[colors.dim]
black = "#191724"
white = "#cfcfd6"
red = "#d95465"
green = "#00d89a"
blue = "#a85561"
yellow = "#d1a514"
magenta = "#e1959f"
cyan = "#767a90"
