[window]
padding = { x = 5, y = 5 }
opacity = 0.8

[font]
size = 16
normal = {family = "JetBrainsMono Nerd Font"}

[terminal.shell]
program = "tmux"
args = ["new-session", "-A", "-s", "main"]

[env]
TERM="xterm-256color"

# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[general]
import = ["rxze49.toml"]
