[colors.primary]
foreground = "#f8eaea"
background = "#181818"
dim_foreground = "#d6cfcf"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#f8eaea"
cursor = "#5e5a7a"

[colors.vi_mode_cursor]
text = "#f8eaea"
cursor = "#5e5a7a"

[colors.search.matches]
foreground = "#f8eaea"
background = "#3a334a"

[colors.search.focused_match]
foreground = "#181818"
background = "#fc5f72"

[colors.hints.start]
foreground = "#f8eaea"
background = "#222222"

[colors.hints.end]
foreground = "#cfcfd6"
background = "#222222"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#f8eaea"
background = "#222222"

[colors.selection]
text = "#f8eaea"
background = "#2a2742"

[colors.normal]
black = "#181818"
red = "#fc5f72"
green = "#00606d"
yellow = "#ffb703"
blue = "#00a7a3"
magenta = "#ff80ab"
cyan = "#767a90"
white = "#f8eaea"

[colors.bright]
black = "#222222"
red = "#ff8a98"
green = "#006475"
yellow = "#ffd75a"
blue = "#01C4BB"
magenta = "#ffd1d7"
cyan = "#9aa0b8"
white = "#ffffff"

[colors.dim]
black = "#141414"
red = "#d44f60"
green = "#00424e"
yellow = "#cc9600"
blue = "#017d83"
magenta = "#e1959f"
cyan = "#5f6377"
white = "#cfcfd6"
